In [19]:
import pandas as pd
import numpy as np

In [12]:
data=pd.read_csv("E:\data_set\day.csv")

In [13]:
data.head(5)

index    dteday  season  yr  mnth  holiday  weekday  workingday  \
0      1  1/1/2011       1   0     1        0        6           0   
1      2  1/2/2011       1   0     1        0        0           0   
2      3  1/3/2011       1   0     1        0        1           1   
3      4  1/4/2011       1   0     1        0        2           1   
4      5  1/5/2011       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [14]:
data.shape

(731, 16)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   index       731 non-null    int64  
 1   dteday      731 non-null    object 
 2   season      731 non-null    int64  
 3   yr          731 non-null    int64  
 4   mnth        731 non-null    int64  
 5   holiday     731 non-null    int64  
 6   weekday     731 non-null    int64  
 7   workingday  731 non-null    int64  
 8   weathersit  731 non-null    int64  
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64  
 14  registered  731 non-null    int64  
 15  cnt         731 non-null    int64  
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB


In [17]:
data.describe()

index      season          yr        mnth     holiday     weekday  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000   
mean   366.000000    2.496580    0.500684    6.519836    0.028728    2.997264   
std    211.165812    1.110807    0.500342    3.451913    0.167155    2.004787   
min      1.000000    1.000000    0.000000    1.000000    0.000000    0.000000   
25%    183.500000    2.000000    0.000000    4.000000    0.000000    1.000000   
50%    366.000000    3.000000    1.000000    7.000000    0.000000    3.000000   
75%    548.500000    3.000000    1.000000   10.000000    0.000000    5.000000   
max    731.000000    4.000000    1.000000   12.000000    1.000000    6.000000   

       workingday  weathersit        temp       atemp         hum   windspeed  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000   
mean     0.683995    1.395349    0.495385    0.474354    0.627894    0.190486   
std      0.465233    0.544894    0.183051    0.162961    0.142429    0.077498   
min      0.000000    1.000000    0.059130    0.079070    0.000000    0.022392   
25%      0.000000    1.000000    0.337083    0.337842    0.520000    0.134950   
50%      1.000000    1.000000    0.498333    0.486733    0.626667    0.180975   
75%      1.000000    2.000000    0.655417    0.608602    0.730209    0.233214   
max      1.000000    3.000000    0.861667    0.840896    0.972500    0.507463   

            casual   registered          cnt  
count   731.000000   731.000000   731.000000  
mean    848.176471  3656.172367  4504.348837  
std     686.622488  1560.256377  1937.211452  
min       2.000000    20.000000    22.000000  
25%     315.500000  2497.000000  3152.000000  
50%     713.000000  3662.000000  4548.000000  
75%    1096.000000  4776.500000  5956.000000  
max    3410.000000  6946.000000  8714.000000

In [20]:
# make an array
array_data= np.array(data)

In [23]:
# separate two columns for first 50 values
array_data_col = array_data[ :50 , [7,8]]

In [26]:
# replace first five values of first column
array_data_col[ :5, 0] = np.array([51,52,53,54,55])

In [28]:
# add first five row values for each column
a3 = array_data_col[ :5 , 0] + array_data_col[ :5 , 1]
print(a3)

[53 54 54 55 56]


In [30]:
array_data_col

array([[51, 2],
       [52, 2],
       [53, 1],
       [54, 1],
       [55, 1],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 2],
       [0, 1],
       [0, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 1],
       [1, 2],
       [0, 1],
       [0, 1],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1]], dtype=object)

In [31]:
# Access the item
print('2nd element on 1st row: ', array_data_col[3, 1])  #(row,col)

2nd element on 1st row:  1


In [32]:
# check shape and size
a4 = np.shape(array_data_col)
a5 = np.size(array_data_col)
print(a4, a5)

(50, 2) 100


In [33]:
# step/interval
print(array_data_col[ : 20 : 2]) 

[[51 2]
 [53 1]
 [55 1]
 [1 2]
 [0 1]
 [1 2]
 [1 1]
 [0 2]
 [0 2]
 [1 2]]


In [34]:
# reshape
a6 = array_data_col.reshape(5,20)
print(a6)

[[51 2 52 2 53 1 54 1 55 1 1 1 1 2 0 2 0 1 1 1]
 [1 2 1 1 1 1 1 1 0 2 0 1 0 2 1 2 1 2 1 2]
 [1 1 0 1 0 1 1 1 1 2 1 3 1 1 1 2 0 1 0 1]
 [1 2 1 2 1 2 1 1 1 2 0 2 0 1 1 1 1 1 1 2]
 [1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1]]


In [35]:
# array split
a7 = np.array_split(array_data_col, 3)
print(a7)

[array([[51, 2],
       [52, 2],
       [53, 1],
       [54, 1],
       [55, 1],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 2],
       [0, 1],
       [0, 2]], dtype=object), array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 1],
       [1, 2],
       [0, 1],
       [0, 1],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 1]], dtype=object), array([[1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1]], dtype=object)]


In [37]:
# transpose
a8 = np.transpose(array_data_col)
print(a8)

[[51 52 53 54 55 1 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1
  1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0]
 [2 2 1 1 1 1 2 2 1 1 2 1 1 1 2 1 2 2 2 2 1 1 1 1 2 3 1 2 1 1 2 2 2 1 2 2
  1 1 1 2 1 1 1 1 1 1 1 1 1 1]]


In [38]:
# join 2 array vertically
b1 = array_data_col
b2 = array_data[ :50, [9,10] ]

In [39]:
# merge verically
b3 = np.concatenate((b1, b2))
print(b3)

[[51 2]
 [52 2]
 [53 1]
 [54 1]
 [55 1]
 [1 1]
 [1 2]
 [0 2]
 [0 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [0 2]
 [0 1]
 [0 2]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 2]
 [1 3]
 [1 1]
 [1 2]
 [0 1]
 [0 1]
 [1 2]
 [1 2]
 [1 2]
 [1 1]
 [1 2]
 [0 2]
 [0 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0.344167 0.363625]
 [0.363478 0.353739]
 [0.196364 0.189405]
 [0.2 0.212122]
 [0.226957 0.22927]
 [0.204348 0.233209]
 [0.196522 0.208839]
 [0.165 0.162254]
 [0.138333 0.116175]
 [0.150833 0.150888]
 [0.169091 0.191464]
 [0.172727 0.160473]
 [0.165 0.150883]
 [0.16087 0.188413]
 [0.233333 0.248112]
 [0.231667 0.234217]
 [0.175833 0.176771]
 [0.216667 0.232333]
 [0.292174 0.298422]
 [0.261667 0.25505]
 [0.1775 0.157833]
 [0.0591304 0.0790696]
 [0.0965217 0.0988391]
 [0.0973913 0.11793]
 [0.223478 0.234526]
 [0.2175 0.2036]
 [0.195 0.2197]
 [0.203478 0.223317]
 [0.196522 0.212126]
 [0.216522 0.250322]
 [0.180833 0.18625]
 [0.192174 0.234

In [40]:
# # index wise  Enumeration
for idx, x in np.ndenumerate(b3):
  print(idx, x) 

(0, 0) 51
(0, 1) 2
(1, 0) 52
(1, 1) 2
(2, 0) 53
(2, 1) 1
(3, 0) 54
(3, 1) 1
(4, 0) 55
(4, 1) 1
(5, 0) 1
(5, 1) 1
(6, 0) 1
(6, 1) 2
(7, 0) 0
(7, 1) 2
(8, 0) 0
(8, 1) 1
(9, 0) 1
(9, 1) 1
(10, 0) 1
(10, 1) 2
(11, 0) 1
(11, 1) 1
(12, 0) 1
(12, 1) 1
(13, 0) 1
(13, 1) 1
(14, 0) 0
(14, 1) 2
(15, 0) 0
(15, 1) 1
(16, 0) 0
(16, 1) 2
(17, 0) 1
(17, 1) 2
(18, 0) 1
(18, 1) 2
(19, 0) 1
(19, 1) 2
(20, 0) 1
(20, 1) 1
(21, 0) 0
(21, 1) 1
(22, 0) 0
(22, 1) 1
(23, 0) 1
(23, 1) 1
(24, 0) 1
(24, 1) 2
(25, 0) 1
(25, 1) 3
(26, 0) 1
(26, 1) 1
(27, 0) 1
(27, 1) 2
(28, 0) 0
(28, 1) 1
(29, 0) 0
(29, 1) 1
(30, 0) 1
(30, 1) 2
(31, 0) 1
(31, 1) 2
(32, 0) 1
(32, 1) 2
(33, 0) 1
(33, 1) 1
(34, 0) 1
(34, 1) 2
(35, 0) 0
(35, 1) 2
(36, 0) 0
(36, 1) 1
(37, 0) 1
(37, 1) 1
(38, 0) 1
(38, 1) 1
(39, 0) 1
(39, 1) 2
(40, 0) 1
(40, 1) 1
(41, 0) 1
(41, 1) 1
(42, 0) 0
(42, 1) 1
(43, 0) 0
(43, 1) 1
(44, 0) 1
(44, 1) 1
(45, 0) 1
(45, 1) 1
(46, 0) 1
(46, 1) 1
(47, 0) 1
(47, 1) 1
(48, 0) 1
(48, 1) 1
(49, 0) 0
(49, 1) 1
(50, 0) 0.34416

In [41]:
# Split the array
b4 = np.array_split(b3, 3)
print(b4)

[array([[51, 2],
       [52, 2],
       [53, 1],
       [54, 1],
       [55, 1],
       [1, 1],
       [1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 2],
       [0, 1],
       [0, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 1],
       [1, 2],
       [0, 1],
       [0, 1],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 1]], dtype=object), array([[1, 2],
       [0, 2],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 2],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0.344167, 0.363625],
       [0.363478, 0.353739],
       [0.196364, 0.189405],
       [0.2, 0.212122],
       [0.226957, 0.22927],
       [0.204348, 0.233209],
       [0.196522, 0.208839],
       [0.165, 0.162254],
     

In [42]:
# sorting array
b4 = np.sort(b3[ : , 0])
print(b4)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.0591304 0.0965217 0.0973913 0.134783
 0.138333 0.144348 0.150833 0.16087 0.165 0.165 0.169091 0.172727 0.175833
 0.1775 0.180833 0.186957 0.189091 0.192174 0.195 0.196364 0.196522
 0.196522 0.2 0.203478 0.204348 0.211304 0.216522 0.216667 0.2175 0.220833
 0.2225 0.223478 0.226957 0.231667 0.233333 0.233333 0.26 0.261667
 0.266087 0.271667 0.285833 0.292174 0.316522 0.318261 0.344167 0.363478
 0.399167 0.415 0.435833 0.521667 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 51 52 53 54 55]


In [43]:
# filter array
b5 = b3[ : , 0] > .5
print(b5)

[ True  True  True  True  True  True  True False False  True  True  True
  True  True False False False  True  True  True  True False False  True
  True  True  True  True False False  True  True  True  True  True False
 False  True  True  True  True  True False False  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False]


In [44]:
print(sum(b3[:, 0]))
print(min(b3[:, 0]))
print(max(b3[:, 0]))
print(np.cumsum(b3[:, 0])) 

307.3542674000002
0
55
[51 103 156 210 265 266 267 267 267 268 269 270 271 272 272 272 272 273
 274 275 276 276 276 277 278 279 280 281 281 281 282 283 284 285 286 286
 286 287 288 289 290 291 291 291 292 293 294 295 296 296 296.344167
 296.707645 296.90400900000003 297.104009 297.33096600000005 297.535314
 297.73183600000004 297.89683600000006 298.03516900000005
 298.18600200000003 298.355093 298.52782 298.69282000000004
 298.85369000000003 299.08702300000004 299.31869000000006
 299.4945230000001 299.71119000000004 300.00336400000003 300.265031
 300.44253100000003 300.50166140000005 300.5981831 300.69557440000005
 300.91905240000006 301.1365524 301.3315524 301.53503040000004
 301.73155240000006 301.94807440000005 302.12890740000006
 302.3210814000001 302.5810814000001 302.7680384000001 302.97934240000006
 303.2126754000001 303.4985084000001 303.7701754000001 303.9910084000001
 304.12579140000014 304.2701394000001 304.45923040000014
 304.68173040000016 304.9982524000002 305.41325240000