In [1]:
import array as arr
import numpy as np


# Check Prime Number

In [2]:
num = int(input("Enter your Prime number :"))
flag =False

if num > 1:
    for x in range(2,num):
        if num % x == 0:
            flag = True
            break

if flag:
    print(f'{num},its not a prime number')
else:
    print(f"{num}, its prime number")

Enter your Prime number :10
10,its not a prime number


# 1. array
# Arrays are a fundamental data structure, and an important part of most programming 
# languages. In Python, they are containers which are able to store more than 
# one item at the same time. they can only hold a sequence of multiple items that
# are of the same type. There are arrays that contain only integers, or only 
# floating point numbers, or only any other Python data type you want to use.

# structure of an array
# variable_name = array(typecode,[elements])

#how you would create an array
# variable_name would be the name of the array.
# The typecode specifies what kind of elements would be stored in the array. 
# Inside square brackets you mention the elements that would be stored in the array, 
# with each element being separated by a comma.

# 'i' 	signed int 	int 	2
# 'l' 	signed long 	int 	4
# 'q' 	signed long long 	int 	8
# 'f' 	float 	float 	4
# 'd' 	double 	float 	8







In [3]:
numbers = arr.array('i',[10,20,30])
print(numbers)


array('i', [10, 20, 30])


In [4]:
print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element

10
20
30


In [5]:
#search for the index of the value 10
print(numbers.index(10))

0


In [6]:
# loop
for number in numbers:
    print(number)

10
20
30


In [7]:
#prints each individual value in the array
for value in range(len(numbers)):
    print(numbers[value])

10
20
30


In [8]:
x=np.array([1,2,3,4,5,6,7])

In [9]:
type(x)

numpy.ndarray

In [10]:
for value in range(len(x)):
  print(x[value])

1
2
3
4
5
6
7


In [11]:
x=arr.array("l",[1,2,3,4,5,6,7])

In [12]:
id(x)

140385803027952

In [13]:
type(x)

array.array

In [14]:
for value in range(len(x)):
  print(x[value])

1
2
3
4
5
6
7


In [15]:
#get the values 10 and 20 only/array slicing
print(numbers[:2])  #first to second position

array('i', [10, 20])


In [16]:
numbers[0] = 40
print(numbers)

array('i', [40, 20, 30])


In [17]:
numbers = arr.array('i',[10,20,30])
print(numbers)

array('i', [10, 20, 30])


In [18]:
numbers.append(100)
print(numbers)

array('i', [10, 20, 30, 100])


In [19]:
numbers.extend([40,50,60])
print(numbers)

array('i', [10, 20, 30, 100, 40, 50, 60])


In [20]:
print(numbers[2] + numbers[3])

130


In [21]:
# Access the item
num = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', num[0, 1]) 

2nd element on 1st row:  2


In [22]:
# 2. numpy methods and functions
# new sample list
a = [ 21,34,16,19,100, 26,29,41,38,59]
ard = np.array(a)
print(ard)

[ 21  34  16  19 100  26  29  41  38  59]


In [23]:
type(ard)

numpy.ndarray

In [24]:
# the number of axes (dimensions) of the array
a = np.ndim(ard)
print(a)

1


In [25]:
# the dimensions of the array
b = np.shape(ard)
print(b)

(10,)


In [26]:
print(ard)

[ 21  34  16  19 100  26  29  41  38  59]


In [27]:
c = np.size(ard)
print(c)

10


In [28]:
print(ard[1:7:2]) 

[34 19 26]


# data types
# Below is a list of all data types in NumPy and the characters used to represent them.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )


In [29]:
print(ard.dtype) 


int64


In [30]:
a2 = np.array(['apple', 'banana', 'cherry'])

print(a2.dtype) 

<U6


In [31]:
# set up array type
a3 = np.array([1, 2, 3, 4], dtype='S')
print(a3)
print(a3.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [32]:
a0=np.array(["bangla","english","biology"])

In [33]:
a0.dtype

dtype('<U7')

In [34]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
a4 = np.array([1.1, 2.1, 3.1])

newarr = a4.astype('i')
# newarr = a4.astype(int)
print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [35]:
a5=np.array([1,2,3,4,5],dtype="i")

In [36]:
a5.dtype

dtype('int32')

In [37]:
x=[[1,2,3,4],[5,6,7,8]]

In [38]:
np.ndim(x)

2

In [39]:
# (lower, upper, interval)
d = np.arange(10,30,3)
print(d)

[10 13 16 19 22 25 28]


In [40]:
# # 50 numbers from 0 to 2 , linear space (lower, upper, no of position)
e =np.linspace(10, 30, 11) 
print(e)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [41]:
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range
x =np.linspace(0, 2, 10)
print("A\n",np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [42]:
a = [ 21,34,16,19,100, 26,29,41,38,59]
ard = np.array(a)
f2 = ard.reshape (2,5)
print(f2)

[[ 21  34  16  19 100]
 [ 26  29  41  38  59]]


In [43]:
np.ndim(f2)

2

In [44]:
i = np.copy(f2)
print(i)

[[ 21  34  16  19 100]
 [ 26  29  41  38  59]]


In [45]:
k2 = [[1,2,3],[3,4,5],[7,8,9]]
k3 = np.mat(k2)
l = np.array_split(k3, 3)
print(l)

[matrix([[1, 2, 3]]), matrix([[3, 4, 5]]), matrix([[7, 8, 9]])]


In [46]:
k3

matrix([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [47]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [48]:
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [50]:
arr

array([1, 2, 3, 4, 5, 6])

In [51]:
k3

matrix([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [52]:
# add column in matrix
k331 = [[10,20,30],[30,40,50],[70,80,90]]
k333 = np.mat(k331)
m = np.column_stack((k3, k333))
print(m)

[[ 1  2  3 10 20 30]
 [ 3  4  5 30 40 50]
 [ 7  8  9 70 80 90]]


In [87]:

# k331 = [[[10,20,30],[30,40,50],[70,80,90]]]
# np.ndim(k331)

In [83]:
n = np.diagonal(m)

In [84]:
n

array([1, 4, 9])

In [55]:
o = np.arange(0,12).reshape(2, 2,3)
print(o)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) #(number_of_matrix,rows,columns)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [82]:
np.ndim(newarr)

2

In [59]:
array4 = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",array4)


Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [60]:
# dsplit
p = np.dsplit(o, 3)
print(p)

[array([[[0],
        [3]],

       [[6],
        [9]]]), array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]])]


In [81]:
np.ndim(p)

4

In [73]:
# transpose matrix
q = np.array([[1, 2], [3, 4], [5, 6]])
j=np.transpose(q)
print("Before transpose\n",q)
print("\n")
print("After Transpose\n",j)

Before transpose
 [[1 2]
 [3 4]
 [5 6]]


After Transpose
 [[1 3 5]
 [2 4 6]]


In [80]:
np.ndim(j)

2

In [75]:
x = np.array([[1, 2], [3, 4], [5, 6]])

In [76]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.ndim(x)

2

In [79]:
# NumPy Joining Array
p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])

p3 = np.concatenate((p1, p2))
print(p3)

[1 2 3 4 5 6]


In [91]:

# Join two 2-D arrays along rows (axis=1)
q1 = np.array([[1, 2], [3, 4]])
q2 = np.array([[5, 6], [7, 8]])

q3 = np.concatenate((q1, q2), axis=1)
print(q3)

[[1 2 5 6]
 [3 4 7 8]]


In [92]:
# Joining Arrays Using Stack Functions
r1 = np.array([1, 2, 3])
r2 = np.array([4, 5, 6])

r3 = np.stack((r1, r2), axis=1)
print(r3) 


[[1 4]
 [2 5]
 [3 6]]


In [93]:
# Stacking Along Rows/ similar to concatanate
s1 = np.array([1, 2, 3])
s2 = np.array([4, 5, 6])

s3 = np.hstack((s1, s2))
print(s3)

[1 2 3 4 5 6]


In [94]:
# Stacking Along Columns
t1 = np.array([1, 2, 3])
t2 = np.array([4, 5, 6])

t3 = np.vstack((t1, t2))
print(t3)

[[1 2 3]
 [4 5 6]]


In [95]:
# Stacking Along Height (depth)
u1 = np.array([1, 2, 3])
u2 = np.array([4, 5, 6])

u3 = np.dstack((u1, u2))
print(u3)

[[[1 4]
  [2 5]
  [3 6]]]
